CREATE TABLE IF NOT EXISTS `shopping`.`customer` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) DEFAULT NULL,
  `last_name` VARCHAR(255) DEFAULT NULL,
  `role` ENUM('ADMIN','CUSTOMER') NOT NULL,
  `address` TEXT DEFAULT NULL,
  PRIMARY KEY (`id`)
) 
ENGINE=InnoDB
AUTO_INCREMENT = 1;