CREATE TABLE IF NOT EXISTS `shopping`.`orders` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `status` ENUM('PENDING','COMPLETED','FAILED') NOT NULL,
  `total_price` DECIMAL (10,2) NOT NULL,
  `total_quantity` INT NOT NULL,
   `customer_id` bigint(20) NOT NULL,
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   FOREIGN KEY (customer_id) REFERENCES customer(id) ON DELETE CASCADE,
  PRIMARY KEY (`id`)
) 
ENGINE=InnoDB
AUTO_INCREMENT = 1;